[project]
authors = ["Ruben Vasquez <ruvasqm@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "AoC Challenges"
name = "AoC"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
